services:
  mysql-payment:
    image: mysql:latest
    restart: always
    container_name: mysql-payment
    hostname: "mysql-payment"
    environment:
      MYSQL_DATABASE: 'paymentdb'
      MYSQL_USER: 'paymentuser_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSqR@@t*2024p@s'
    ports:
      - '3309:3306' # Porta externa:porta interna
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-payment" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - my_network


  mspayment:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-payment:
        condition: service_healthy
    hostname: "ms-payment"
    environment:
      MYSQL_HOSTNAME: mysql-payment
      MYSQL_PORT: 3306 # Porta interna usada para comunicação entre containers
      MSUSER_HOSTNAME: ms-user
      MSUSER_PORT: 8080
    ports:
      - 8083:8083
    networks:
      - my_network


  sonarqube:
    image: sonarqube:community
    hostname: "sonarqube"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9003:9000"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  my_network:
    driver: bridge
    external: true